fragment artwork on Artwork {
  id
  artist {
    id
    name
  }
  category
  date
  href
  image {
    image_versions
    image_url
  }
  title
  displayLabel
  price
  is_for_sale
}

query ArtworksQuery {
 	filter_artworks(
    acquireable: true,
    for_sale: true,
    aggregations: PRICE_RANGE,
  ) {
    hits {
      ...artwork
    }
  }
}
